name: R-CMD-check

on:
   push:
     branches:
      - master
   pull_request:
     branches:
       - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v1
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ runner.os }}-r-${{ '4.0' }}-${{ hashFiles('DESCRIPTION') }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update && apt-get install -y --no-install-recommends \
          texlive \
          libxml2-dev \
          libssl-dev \
          libcairo2-dev \
          libxt-dev \
          libpng-dev \
          libudunits2-dev \
          libcurl4-openssl-dev
          sudo apt autoremove -y
      - name: Install Package Dependencies
        run: |-
          Rscript -e "remotes::install_deps(dependencies = TRUE, upgrade = 'default', repos = 'https://mirror.las.iastate.edu/CRAN/')"
      - name: Check Package
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error', check_dir = 'check', args = '--no-manual')"
